# This workflow builds and publishes the Python package to PyPI when a release is created.

name: Publish Python Package to PyPI

on:
  release:
    types: [published] # Trigger only when a release is published (not pre-release)

permissions:
  contents: read
  # This permission is needed for twine to upload distributions.
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version like '3.11' or keep '3.x' for latest 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No API token needed here if using trusted publishing (recommended)
      # If not using trusted publishing, uncomment the lines below and add PYPI_API_TOKEN secret
      # with:
      #   user: __token__
      #   password: ${{ secrets.PYPI_API_TOKEN }}